main: org.skriptlang.skriptworldguard.SkriptWorldGuard
api-version: 1.13
name: skript-worldguard
authors: ['SkriptLang Team', Contributors]
description: Official WorldGuard 7 Addon for Skript
version: @version@
website: https://github.com/SkriptLang/skript-worldguard
softdepend: [Skript, WorldGuard]
